version: "3"
services: 
    app:
        build: .
        image: ccdb-app
        container_name: ccdb-app
        depends_on:
            - database
            - redis
        ports:
            - "8080:8080"
        links:
            - database:database
            - redis:redis
        volumes:
            - .:/srv/app
        env_file: .docker.env
    database:
        container_name: ccdb-db
        image: mysql:5.7
        ports:
            - "13306:3306"
        volumes:
            - ./.docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=ccdb
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=ccdb
            - MYSQL_USER=password
    redis:
        image: centos/redis-5-centos7
        ports:
            - "6379:6379"
        environment:
            - REDIS_PASSWORD=beans
    artisan:
        image: ccdb-app
        container_name: ccdb-artisan
        volumes:
            - .:/srv/app
        entrypoint: [
            "php",
            "/srv/app/artisan"
        ]
    