apiVersion: v1
kind: Service
metadata:
  labels:
    app: queue
  name: queue
  namespace: dept-communitycuration
  selfLink: /api/v1/namespaces/dept-communitycuration/services/queue
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: queue
    deploymentconfig: queue
  sessionAffinity: None
status:
  loadBalancer: {}
