apiVersion: v1
kind: Service
metadata:
  labels:
    app: scheduler
  name: scheduler
  namespace: dept-communitycuration
  selfLink: /api/v1/namespaces/dept-communitycuration/services/scheduler
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: scheduler
    deploymentconfig: scheduler
  sessionAffinity: None
status:
  loadBalancer: {}
